### ISSUE TITLE
Login crashes after installation on macOS sierra

### ISSUE THREAD

**Issue by EliyahuStern** [jzdziarski/littleflocker#18]
I had to reboot in safe mode to uninstall the kext.

Panic:

Anonymous UUID:       46B1B423-EB38-977D-2201-46EFB55042D4

Wed Aug 24 12:01:35 2016

*** Panic Report ***
panic(cpu 3 caller 0xffffff801f809f3a): Kernel trap at 0xffffff7fa264c9d4, type 14=page fault, registers:
CR0: 0x0000000080010033, CR2: 0x000000010fbbf690, CR3: 0x0000000015c35063, CR4: 0x00000000003627e0
RAX: 0x00000000000000fd, RBX: 0x000000010fbbf690, RCX: 0xffffffffffffffc0, RDX: 0xffffff81bc0581a8
RSP: 0xffffff9209a8bd70, RBP: 0xffffff9209a8bd90, RSI: 0xffffff8042e83260, RDI: 0x000000010fbbf691
R8:  0x0000000000000000, R9:  0xffffff81bc0581a9, R10: 0x00000000ffe00001, R11: 0x00007fffffe00000
R12: 0x0000000000000001, R13: 0x0000000000000000, R14: 0xffffff8042e83260, R15: 0xffffff81bc057000
RFL: 0x0000000000010246, RIP: 0xffffff7fa264c9d4, CS:  0x0000000000000008, SS:  0x0000000000000010
Fault CR2: 0x000000010fbbf690, Error code: 0x0000000000000001, Fault CPU: 0x3 SMAP fault, PL: 0

Backtrace (CPU 3), Frame : Return Address
0xffffff9209a8ba00 : 0xffffff801f6f748c 
0xffffff9209a8ba80 : 0xffffff801f809f3a 
0xffffff9209a8bc60 : 0xffffff801f6a9743 
0xffffff9209a8bc80 : 0xffffff7fa264c9d4 
0xffffff9209a8bd90 : 0xffffff7fa264eae6 
0xffffff9209a8bda0 : 0xffffff801f7c9e93 
0xffffff9209a8bdd0 : 0xffffff801f6fc23c 
0xffffff9209a8be30 : 0xffffff801f6d9b51 
0xffffff9209a8be80 : 0xffffff801f6ed6e7 
0xffffff9209a8bf10 : 0xffffff801f7f5ffe 
0xffffff9209a8bfb0 : 0xffffff801f6a9f66 
      Kernel Extensions in backtrace:
         com.zdziarski.LittleFlocker(1.0)[024F206E-AF9C-350D-8ECB-68C1223BC016]@0xffffff7fa264a000->0xffffff7fa2650fff

BSD process name corresponding to current thread: LittleFlockerDae

Mac OS version:
16A294a

Kernel version:
Darwin Kernel Version 16.0.0: Fri Aug 12 19:00:53 PDT 2016; root:xnu-3789.1.28~1/RELEASE_X86_64
Kernel UUID: E5CACC64-93F3-350C-B316-0121268AD826
Kernel slide:     0x000000001f400000
Kernel text base: 0xffffff801f600000
__HIB  text base: 0xffffff801f500000
System model name: MacBookPro12,1 (Mac-E43C1C25D4880AD6)

System uptime in nanoseconds: 6981652864
last loaded kext at 4963784918: com.apple.filesystems.autofs	3.0 (addr 0xffffff7fa18a3000, size 45056)
loaded kexts:
com.zdziarski.LittleFlocker	1
com.apple.filesystems.autofs	3.0
com.apple.driver.AudioAUUC	1.70
com.apple.driver.AGPM	110.23.7
com.apple.driver.ApplePlatformEnabler	2.7.0d0
com.apple.driver.X86PlatformShim	1.0.0
com.apple.driver.AppleOSXWatchdog	1
com.apple.driver.AppleGraphicsDevicePolicy	3.13.60
com.apple.driver.AppleUpstreamUserClient	3.6.4
com.apple.driver.AppleHDAHardwareConfigDriver	276.23
com.apple.driver.AppleHDA	276.23
com.apple.driver.AppleIntelBDWGraphics	10.1.8
com.apple.driver.AppleThunderboltIP	3.0.8
com.apple.driver.pmtelemetry	1
com.apple.iokit.IOUserEthernet	1.0.1
com.apple.iokit.IOBluetoothSerialManager	5.0.0f5
com.apple.Dont_Steal_Mac_OS_X	7.0.0
com.apple.driver.AppleHV	1
com.apple.driver.AppleMuxControl	3.13.60
com.apple.driver.AppleBacklight	170.9.10
com.apple.driver.AppleMCCSControl	1.2.13
com.apple.iokit.BroadcomBluetoothHostControllerUSBTransport	5.0.0f5
com.apple.driver.AppleSMCLMU	208
com.apple.driver.AppleLPC	3.1
com.apple.driver.AppleCameraInterface	5.57.0
com.apple.driver.AppleIntelSlowAdaptiveClocking	4.0.0
com.apple.driver.AppleFIVRDriver	4.1.0
com.apple.driver.ACPI_SMC_PlatformPlugin	1.0.0
com.apple.driver.AppleIntelBDWGraphicsFramebuffer	10.1.8
com.apple.iokit.SCSITaskUserClient	394
com.apple.iokit.IOBluetoothUSBDFU	5.0.0f5
com.apple.driver.AppleUSBStorageCoexistentDriver	404.1.1
com.apple.driver.AppleUSBCardReader	404.1.1
com.apple.driver.CoreStorageFsck	540
com.apple.driver.AppleFileSystemDriver	3.0.1
com.apple.AppleFSCompression.AppleFSCompressionTypeDataless	1.0.0d1
com.apple.AppleFSCompression.AppleFSCompressionTypeZlib	1.0.0
com.apple.BootCache	39
com.apple.filesystems.hfs.kext	366
com.apple.iokit.IOAHCIBlockStorage	295.1.1
com.apple.driver.AppleAHCIPort	326
com.apple.driver.AppleTopCaseHIDEventDriver	102
com.apple.iokit.AppleBCM5701Ethernet	10.2.6
com.apple.driver.AirPort.Brcm4360	1100.37.1a16
com.apple.driver.AppleRTC	2.0
com.apple.driver.AppleSmartBatteryManager	161.0.0
com.apple.driver.AppleHPET	1.8
com.apple.driver.AppleACPIButtons	5.0
com.apple.driver.AppleSMBIOS	2.1
com.apple.driver.AppleACPIEC	5.0
com.apple.driver.AppleAPIC	1.7
com.apple.nke.applicationfirewall	170
com.apple.security.quarantine	3
com.apple.security.TMSafetyNet	8
com.apple.kext.triggers	1.0
com.apple.driver.DspFuncLib	276.23
com.apple.kext.OSvKernDSPLib	525
com.apple.driver.AppleThunderboltEDMSink	4.1.1
com.apple.driver.AppleThunderboltDPOutAdapter	4.5.3
com.apple.iokit.IOSurface	152
com.apple.driver.AppleGraphicsControl	3.13.60
com.apple.driver.AppleBacklightExpert	1.1.0
com.apple.iokit.IONDRVSupport	2.4.1
com.apple.driver.AppleSMBusController	1.0.14d1
com.apple.iokit.IOBluetoothHostControllerUSBTransport	5.0.0f5
com.apple.iokit.IOBluetoothHostControllerTransport	5.0.0f5
com.apple.iokit.IOBluetoothFamily	5.0.0f5
com.apple.iokit.IOSlowAdaptiveClockingFamily	1.0.0
com.apple.driver.AppleHDAController	276.23
com.apple.iokit.IOHDAFamily	276.23
com.apple.iokit.IOAudioFamily	205.11
com.apple.vecLib.kext	1.2.0
com.apple.driver.IOPlatformPluginLegacy	1.0.0
com.apple.driver.X86PlatformPlugin	1.0.0
com.apple.driver.AppleSMC	3.1.9
com.apple.driver.IOPlatformPluginFamily	6.0.0d8
com.apple.driver.AppleSMBusPCI	1.0.14d1
com.apple.driver.AppleIntelLpssUARTv0	3.0.60
com.apple.driver.AppleIntelLpssUARTCommon	3.0.60
com.apple.iokit.IOSerialFamily	11
com.apple.AppleGraphicsDeviceControl	3.13.60
com.apple.iokit.IOAcceleratorFamily2	288.13
com.apple.iokit.IOGraphicsFamily	2.4.1
com.apple.driver.usb.IOUSBHostHIDDevice	1.1
com.apple.iokit.IOUSBMassStorageClass	4.0.4
com.apple.iokit.IOSCSIBlockCommandsDevice	394
com.apple.iokit.IOUSBMassStorageDriver	131.1.1
com.apple.iokit.IOSCSIArchitectureModelFamily	394
com.apple.driver.usb.cdc	5.0.0
com.apple.driver.usb.networking	5.0.0
com.apple.driver.usb.AppleUSBHostCompositeDevice	1.1
com.apple.driver.usb.AppleUSBHub	1.1
com.apple.driver.AppleThunderboltDPInAdapter	4.5.3
com.apple.driver.AppleThunderboltDPAdapterFamily	4.5.3
com.apple.driver.AppleThunderboltPCIUpAdapter	2.0.3
com.apple.driver.AppleThunderboltPCIDownAdapter	2.0.3
com.apple.driver.CoreStorage	540
com.apple.filesystems.hfs.encodings.kext	1
com.apple.driver.AppleUSBMergeNub	900.4.1
com.apple.driver.AppleXsanScheme	3
com.apple.iokit.IOAHCIFamily	288
com.apple.driver.AppleHIDKeyboard	197
com.apple.driver.AppleMultitouchDriver	367.5
com.apple.driver.AppleInputDeviceSupport	76.1
com.apple.driver.AppleHSSPIHIDDriver	49
com.apple.iokit.IOEthernetAVBController	1.0.3b4
com.apple.driver.AppleThunderboltNHI	4.1.3
com.apple.iokit.IOThunderboltFamily	6.2.1
com.apple.iokit.IO80211Family	1200.12.2
com.apple.driver.mDNSOffloadUserClient	1.0.1b8
com.apple.iokit.IONetworkingFamily	3.2
com.apple.driver.corecapture	1.0.4
com.apple.driver.AppleHSSPISupport	49
com.apple.driver.AppleIntelLpssSpiController	3.0.60
com.apple.driver.AppleIntelLpssI2C	3.0.60
com.apple.driver.AppleIntelLpssGspi	3.0.60
com.apple.driver.AppleIntelLpssDmac	3.0.60
com.apple.driver.usb.AppleUSBXHCIPCI	1.1
com.apple.driver.usb.AppleUSBXHCI	1.1
com.apple.driver.usb.AppleUSBHostPacketFilter	1.0
com.apple.iokit.IOUSBFamily	900.4.1
com.apple.iokit.IOUSBHostFamily	1.1
com.apple.driver.AppleUSBHostMergeProperties	1.1
com.apple.driver.AppleBusPowerController	1.0
com.apple.driver.AppleEFINVRAM	2.1
com.apple.driver.AppleEFIRuntime	2.0
com.apple.iokit.IOHIDFamily	2.0.0
com.apple.iokit.IOSMBusFamily	1.1
com.apple.security.sandbox	300.0
com.apple.kext.AppleMatch	1.0.0d1
com.apple.driver.AppleKeyStore	2
com.apple.driver.AppleMobileFileIntegrity	1.0.5
com.apple.driver.AppleCredentialManager	1.0
com.apple.driver.DiskImages	444
com.apple.iokit.IOStorageFamily	2.1
com.apple.iokit.IOReportFamily	31
com.apple.driver.AppleFDEKeyStore	28.30
com.apple.driver.AppleACPIPlatform	5.0
com.apple.iokit.IOPCIFamily	2.9
com.apple.iokit.IOACPIFamily	1.4
com.apple.kec.Libm	1
com.apple.kec.pthread	1
com.apple.kec.corecrypto	1.0

**Comment by jzdziarski** [comment]
Hi, which build was this?

**Comment by EliyahuStern** [comment]
Installed with LittleFlocker-0.0.63a.pkg

**Comment by jzdziarski** [comment]
Hi. Could you please give 64 a try and see if the changes corrected this? If not can you send another panic log? Thanks!

**Comment by ianatha** [comment]
This happens on Darwin Kernel Version 15.6.0 with LittleFlocker-0.0.65a.pkg upon kextload-ing the kext:

```
Anonymous UUID:       BA6E204D-28BD-2C41-6379-DE85E8718991

Wed Aug 24 16:32:26 2016

*** Panic Report ***
panic(cpu 1 caller 0xffffff801d1ce6fa): Kernel trap at 0xffffff7f9f025914, type 14=page fault, registers:
CR0: 0x0000000080010033, CR2: 0x0000000101293290, CR3: 0x000000000d03a09f, CR4: 0x00000000003606e0
RAX: 0x000000000000001e, RBX: 0x0000000101293290, RCX: 0xffffffffffffffc0, RDX: 0xffffff8052e8a168
RSP: 0xffffff807c6f3dd0, RBP: 0xffffff807c6f3df0, RSI: 0xffffff8026817dc0, RDI: 0x0000000101293291
R8:  0x0000000000000000, R9:  0xffffff8052e8a169, R10: 0x00007fffffe00000, R11: 0xffffff8024e61ea8
R12: 0x0000000000000000, R13: 0x0000000000000003, R14: 0xffffff8026817dc0, R15: 0xffffff8052e89000
RFL: 0x0000000000010246, RIP: 0xffffff7f9f025914, CS:  0x0000000000000008, SS:  0x0000000000000010
Fault CR2: 0x0000000101293290, Error code: 0x0000000000000001, Fault CPU: 0x1 VMM SMAP fault, PL: 0

Backtrace (CPU 1), Frame : Return Address
0xffffff807c6f3a60 : 0xffffff801d0dab52 
0xffffff807c6f3ae0 : 0xffffff801d1ce6fa 
0xffffff807c6f3cc0 : 0xffffff801d1ec563 
0xffffff807c6f3ce0 : 0xffffff7f9f025914 
0xffffff807c6f3df0 : 0xffffff7f9f027ae6 
0xffffff807c6f3e00 : 0xffffff801d1984c3 
0xffffff807c6f3e30 : 0xffffff801d0df2c3 
0xffffff807c6f3e60 : 0xffffff801d0c28f8 
0xffffff807c6f3ea0 : 0xffffff801d0d26a5 
0xffffff807c6f3f10 : 0xffffff801d1b8eca 
0xffffff807c6f3fb0 : 0xffffff801d1ecd86 
      Kernel Extensions in backtrace:
         com.zdziarski.LittleFlocker(1.0)[9EEE7AD1-D119-333D-9B26-664117F21264]@0xffffff7f9f023000->0xffffff7f9f032fff

BSD process name corresponding to current thread: LittleFlockerUse

Mac OS version:
15G31

Kernel version:
Darwin Kernel Version 15.6.0: Thu Jun 23 18:25:34 PDT 2016; root:xnu-3248.60.10~1/RELEASE_X86_64
Kernel UUID: B5AA8E3E-65B6-3D0E-867B-8DCCF81E536C
Kernel slide:     0x000000001ce00000
Kernel text base: 0xffffff801d000000
__HIB  text base: 0xffffff801cf00000
System model name: [...]

System uptime in nanoseconds: 218023762014
last loaded kext at 215934631659: com.zdziarski.LittleFlocker	1 (addr 0xffffff7f9f023000, size 65536)
last unloaded kext at 164995791053: com.apple.driver.AppleFileSystemDriver	3.0.1 (addr 0xffffff7f9ef59000, size 8192)
loaded kexts:
com.zdziarski.LittleFlocker	1
com.apple.driver.AudioAUUC	1.70
[...]
```

**Comment by jzdziarski** [comment]
ianatha- which build is that, 64, 65?

**Comment by jzdziarski** [comment]
never mind, just saw your comment. i'll look into it. thanks.

**Comment by jzdziarski** [comment]
crash is at 0x2914, will investigate

LittleFlocker`com_zdziarski_driver_LittleFlocker::setMachPort:
LittleFlocker[0x286e] <+0>:   pushq  %rbp
LittleFlocker[0x286f] <+1>:   movq   %rsp, %rbp
LittleFlocker[0x2872] <+4>:   pushq  %r15
LittleFlocker[0x2874] <+6>:   pushq  %r14
LittleFlocker[0x2876] <+8>:   pushq  %r12
LittleFlocker[0x2878] <+10>:  pushq  %rbx
LittleFlocker[0x2879] <+11>:  movq   %rcx, %rbx
LittleFlocker[0x287c] <+14>:  movl   %edx, %r12d
LittleFlocker[0x287f] <+17>:  movq   %rsi, %r14
LittleFlocker[0x2882] <+20>:  movq   %rdi, %r15
LittleFlocker[0x2885] <+23>:  testq  %rbx, %rbx
LittleFlocker[0x2888] <+26>:  je     0x28ef                    ; <+129>
LittleFlocker[0x288a] <+28>:  movq   0x1138(%r15), %rdi
LittleFlocker[0x2891] <+35>:  callq  0x2896                    ; <+40>
LittleFlocker[0x2896] <+40>:  testb  %r12b, %r12b
LittleFlocker[0x2899] <+43>:  je     0x28f3                    ; <+133>
LittleFlocker[0x289b] <+45>:  leaq   0x11a8(%r15), %rdx
LittleFlocker[0x28a2] <+52>:  xorl   %r8d, %r8d
LittleFlocker[0x28a5] <+55>:  movq   $-0x40, %rcx
LittleFlocker[0x28ac] <+62>:  leaq   0x1(%rdx), %r9
LittleFlocker[0x28b0] <+66>:  leaq   0x1(%rbx), %rdi
LittleFlocker[0x28b4] <+70>:  testl  %r8d, %r8d
LittleFlocker[0x28b7] <+73>:  jne    0x28cc                    ; <+94>
LittleFlocker[0x28b9] <+75>:  movzbl (%rdx), %eax
LittleFlocker[0x28bc] <+78>:  movzbl (%rbx), %esi
LittleFlocker[0x28bf] <+81>:  subl   %esi, %eax
LittleFlocker[0x28c1] <+83>:  je     0x28cc                    ; <+94>
LittleFlocker[0x28c3] <+85>:  movl   %eax, %r8d
LittleFlocker[0x28c6] <+88>:  movq   %rdx, %r9
LittleFlocker[0x28c9] <+91>:  movq   %rbx, %rdi
LittleFlocker[0x28cc] <+94>:  incq   %rcx
LittleFlocker[0x28cf] <+97>:  movq   %r9, %rdx
LittleFlocker[0x28d2] <+100>: movq   %rdi, %rbx
LittleFlocker[0x28d5] <+103>: jne    0x28ac                    ; <+62>
LittleFlocker[0x28d7] <+105>: testl  %r8d, %r8d
LittleFlocker[0x28da] <+108>: jne    0x293e                    ; <+208>
LittleFlocker[0x28dc] <+110>: cmpq   $0x0, 0x90(%r15)
LittleFlocker[0x28e4] <+118>: jne    0x293e                    ; <+208>
LittleFlocker[0x28e6] <+120>: movq   %r14, 0x90(%r15)
LittleFlocker[0x28ed] <+127>: jmp    0x295e                    ; <+240>
LittleFlocker[0x28ef] <+129>: xorl   %ebx, %ebx
LittleFlocker[0x28f1] <+131>: jmp    0x294c                    ; <+222>
LittleFlocker[0x28f3] <+133>: leaq   0x1168(%r15), %rdx
LittleFlocker[0x28fa] <+140>: xorl   %r8d, %r8d
LittleFlocker[0x28fd] <+143>: movq   $-0x40, %rcx
LittleFlocker[0x2904] <+150>: leaq   0x1(%rdx), %r9
LittleFlocker[0x2908] <+154>: leaq   0x1(%rbx), %rdi
LittleFlocker[0x290c] <+158>: testl  %r8d, %r8d
LittleFlocker[0x290f] <+161>: jne    0x2924                    ; <+182>
LittleFlocker[0x2911] <+163>: movzbl (%rdx), %eax
LittleFlocker[0x2914] <+166>: movzbl (%rbx), %esi
LittleFlocker[0x2917] <+169>: subl   %esi, %eax

**Comment by ianatha** [comment]
I think `memcpy_s` causes it.

```* thread #15: tid = 0x0bfd, 0xffffff7f85c53a2e LittleFlocker`com_zdziarski_driver_LittleFlocker::setMachPort(ipc_port*, bool, unsigned char*) + 16 at LittleFlocker.cpp:37, name = '0xffffff800b369540', queue = '0x0', stop reason = EXC_BAD_ACCESS (code=5, address=0xc238290)
    frame #0: 0xffffff7f85c53a2e LittleFlocker`com_zdziarski_driver_LittleFlocker::setMachPort(ipc_port*, bool, unsigned char*) + 16 at LittleFlocker.cpp:37 [opt]
   34  	        const unsigned char *p1 = (unsigned char *)s1, *p2 = (unsigned char *)s2;
   35  	        do {
   36  	            if (*p1++ != *p2++ && !ret)
-> 37  	                ret = (*--p1 - *--p2);
   38  	        } while (--n != 0);
   39  	    }
   40  	    return ret;
(lldb) bt
* thread #15: tid = 0x0bfd, 0xffffff7f85c53a2e LittleFlocker`com_zdziarski_driver_LittleFlocker::setMachPort(ipc_port*, bool, unsigned char*) + 16 at LittleFlocker.cpp:37, name = '0xffffff800b369540', queue = '0x0', stop reason = EXC_BAD_ACCESS (code=5, address=0xc238290)
  * frame #0: 0xffffff7f85c53a2e LittleFlocker`com_zdziarski_driver_LittleFlocker::setMachPort(ipc_port*, bool, unsigned char*) + 16 at LittleFlocker.cpp:37 [opt]
    frame #1: 0xffffff7f85c53a1e LittleFlocker`com_zdziarski_driver_LittleFlocker::setMachPort(this=0xffffff803a464000, port=0xffffff800d7ceac0, is_daemon=<unavailable>, skey=<unavailable>) + 150 at LittleFlocker.cpp:430 [opt]
    frame #2: 0xffffff7f85c55ae8 LittleFlocker`com_zdziarski_driver_LittleFlockerClient::registerNotificationPort(this=<unavailable>, port=<unavailable>, type=<unavailable>, refCon=<unavailable>) + 26 at LittleFlockerClient.cpp:173 [opt]
    frame #3: 0xffffff8003d58c83 kernel.development`_Xio_connect_set_notification_port_64(InHeadP=0xffffff800e699f74, OutHeadP=0xffffff800f8e1890) + 115 at device_server.c:8558 [opt]
    frame #4: 0xffffff8003c83443 kernel.development`ipc_kobject_server(request=0xffffff800e699f00) + 259 at ipc_kobject.c:340 [opt]
    frame #5: 0xffffff8003c5ef03 kernel.development`ipc_kmsg_send(kmsg=<unavailable>, option=<unavailable>, send_timeout=0) + 211 at ipc_kmsg.c:1443 [opt]
    frame #6: 0xffffff8003c75985 kernel.development`mach_msg_overwrite_trap(args=<unavailable>) + 197 at mach_msg.c:474 [opt]
    frame #7: 0xffffff8003d7f000 kernel.development`mach_call_munger64(state=0xffffff800b347f80) + 480 at bsd_i386.c:560 [opt]
    frame #8: 0xffffff8003db4de6 kernel.development`hndl_mach_scall64 + 22
```

```(lldb) fr v
(size_t) n = 64
(int) ret = 0
(const unsigned char *) p1 = 0xffffff803a465169 "\fJLr\x7ft"
(const unsigned char *) p2 = 0x000000010c238290 ""
```

**Comment by jzdziarski** [comment]
after reading some more source, I think I may be using registerNotificationPort wrong, I'm going to make some tweaks. please try out build #66 which should be up shortly after some basic testing.

**Comment by ianatha** [comment]
Indeed, it looks like `unsigned char *skey` isn’t what it’s expected to be at setMachPort.

The comment for `com_zdziarski_driver_LittleFlocker::genSecurityKey` mentions sending it over mach messages—-where’s the code that sends the newly nascent skey to the Client?

**Comment by jzdziarski** [comment]
in my calls to IOConnectSetNotificationPort, was passing the skey, but after reading the IOKit docs it doesn't look like you can pass memory around that way, like you can with IOConnectCallMethod; skey isn't really necessary for setting the mach port anyway, so I've removed it for now, i'll push a build shortly.

**Comment by ianatha** [comment]
:heart:

**Comment by jzdziarski** [comment]
build 66 is up! please let me know if this addresses the problem.

**Comment by ianatha** [comment]
Kernel panics at a different location now:

port->ip_receiver != ipc_space_kernel

<img width="1027" alt="screen shot 2016-08-24 at 7 21 10 pm" src="https://cloud.githubusercontent.com/assets/38443/17954443/005eb5a0-6a30-11e6-8359-a90189363b88.png">

**Comment by jzdziarski** [comment]
I am wondering if your launch daemon is loading earlier than mine and it can't create a mach port. i've committed some code to fix possible issues around that. can you build a new kext and give it a try? if it does fail to create a mach port then now it should add that to the daemon log in /Library/Logs

**Comment by jzdziarski** [comment]
sorry, the changes are in the daemon, not the kext.

**Comment by ianatha** [comment]
👀

**Comment by jzdziarski** [comment]
actually maybe best to recompile both the kext and daemon

**Comment by jzdziarski** [comment]
i found a couple null pointer checks that were missing in the kext, which i've committed, and one in the daemon... fingers crossed. let me know if it works.

**Comment by ianatha** [comment]
Tried commit a641d69f8a00fcbfc89ba271e83afdc87c137d0b in a VM running a clean installation of El Capitan.

Still getting a kernel panic.

<img width="1026" alt="screen shot 2016-08-24 at 8 32 15 pm" src="https://cloud.githubusercontent.com/assets/38443/17955836/e98220ce-6a39-11e6-8d4a-5266185cdd54.png">

FWIW, my kext is signed (my dev certificate has the kext signing entitlement) and SIP is enabled fully.

Thank you for all your help, Jonathan.

**Comment by jzdziarski** [comment]
just out of curiosity does it work unsigned

**Comment by jzdziarski** [comment]
mach dispositions mabbe?

**Comment by ianatha** [comment]
It works with SIP disabled.

I don't know what "mach dispositions" means (and Google wasn't helpful either).

**Comment by ianatha** [comment]
Signing the extension, and leaving SIP off still makes it work.
The moment SIP is enabled, it kernel panics.

though this is now a separate issue, and we've successfully resolved the kernel panic originally reported.

**Comment by jzdziarski** [comment]
the assertion seems to be in ./osfmk/ipc/ipc_object.c in xnu and may be related to the MAKE_SEND msg bit

**Comment by ianatha** [comment]
Commit a641d69f8a00fcbfc89ba271e83afdc87c137d0b, SIP on, KEXT signed, on real machine; installed without problems 😄 

this is beautiful 👍 

not sure what was going wrong in the VM; i'll give it another try tomorrow

**Comment by jzdziarski** [comment]
based on the xnu source, i am sending those messages with the wrong sender rights, so it wouldn't surprise me if that's at work too... nonetheless i've corrected those in one last commit for the night, will push 67a out shortly, if you want to test the final code for the night, that'd be helpful, thanks!

**Comment by ianatha** [comment]
:) testing 67a

**Comment by ianatha** [comment]
67a tested, with kext signed and SIP enabled inside a clean El Capitan VM

**Comment by jzdziarski** [comment]
thanks, going to close this out then - feel free to open it if the issue rises again. thanks for all your testing efforts!

**Comment by EliyahuStern** [comment]
67a works for me as well!
