### ISSUE TITLE
System freeze when opening Steam

### ISSUE THREAD

**Issue by TvdW** [jzdziarski/littleflocker#61]
Just installed Little Flocker, works great so far... except for one program: Steam (steampowered.com)

Within ten seconds of opening it, my system freezes and needs a hard reset. The pointer can still be moved.

The littleflocker log (I truncated it before opening Steam) :

```
[09/12/2016 21:43:46] 90 void notificationCallback(CFMachPortRef, void *, CFIndex, void *): received notification callback type 100
[09/12/2016 21:43:46] 90 void *handlePolicyQuery(void *): received policy query for pid 773 target /Users/tomvanderwoerdt/Library/Application Support/Steam/Steam.AppBundle/Steam/Contents/MacOS/Frameworks/Chromium Embedded Framework.framework/Chromium Embedded Framework process /Users/tomvanderwoerdt/Library/Application Support/Steam/Steam.AppBundle/Steam/Contents/MacOS/Frameworks/Steam Helper.app/Contents/MacOS/Steam Helper parent /bin/sh op 1
[09/12/2016 21:43:46] 90 int promptUserForPermission(struct policy_query *): getting console user
[09/12/2016 21:43:46] 90 int promptUserForPermission(struct policy_query *): console uid 501
[09/12/2016 21:43:46] 90 int promptUserForPermission(struct policy_query *): checking codesign
[09/12/2016 21:43:46] 90 int promptUserForPermission(struct policy_query *): codesign state is 1
[09/12/2016 21:43:46] 90 int promptUserForPermission(struct policy_query *): codesign identity is (null)
[09/12/2016 21:43:46] 90 int promptUserForPermission(struct policy_query *): bundle path is /Users/tomvanderwoerdt/Library/Application Support/Steam/Steam.AppBundle/Steam/Contents/MacOS/Frameworks/Steam Helper.app
[09/12/2016 21:43:46] 90 int promptUserForPermission(struct policy_query *): bundle codesign state is 1
[09/12/2016 21:43:46] 90 int promptUserForPermission(struct policy_query *): loaded bundle for path /Users/tomvanderwoerdt/Library/Application Support/Steam/Steam.AppBundle/Steam/Contents/MacOS/Frameworks/Steam Helper.app
[09/12/2016 21:43:46] 90 int promptUserForPermission(struct policy_query *): building path hierarchy
[09/12/2016 21:43:46] 90 int promptUserForPermission(struct policy_query *): getting pidpath for 773
[09/12/2016 21:43:46] 90 int promptUserForPermission(struct policy_query *): pid is alive
[09/12/2016 21:43:46] 90 int promptUserForPermission(struct policy_query *): manicuring display and app names
[09/12/2016 21:43:46] 90 int promptUserForPermission(struct policy_query *): displayName: Steam Helper via /bin/sh
[09/12/2016 21:43:46] 90 int promptUserForPermission(struct policy_query *): proc_path: /Users/tomvanderwoerdt/Library/Application Support/Steam/Steam.AppBundle/Steam/Contents/MacOS/Frameworks/Steam Helper.app/Contents/MacOS/Steam Helper
[09/12/2016 21:43:46] 90 int promptUserForPermission(struct policy_query *): Little Flocker detected a read attempt to the file:
/Users/tomvanderwoerdt/Library/Application Support/Steam/Steam.AppBundle/Steam/Contents/MacOS/Frameworks/Chromium Embedded Framework.framework/Chromium Embedded Framework

Application:
/Users/tomvanderwoerdt/Library/Application Support/Steam/Steam.AppBundle/Steam/Contents/MacOS/Frameworks/Steam Helper.app/Contents/MacOS/Steam Helper (773)

Parent:
/Users/tomvanderwoerdt/Library/Application Support/Steam/Steam.AppBundle/Steam/Contents/MacOS/steam_osx (772)

Codesign Identity: Unknown

Warning: This application is unsigned, and could harm your computer.


[09/12/2016 21:43:46] 90 int promptUserForPermission(struct policy_query *): $HOME is /Users/tomvanderwoerdt
[09/12/2016 21:43:46] 90 int promptUserForPermission(struct policy_query *): codesign state: 1
[09/12/2016 21:43:46] 90 int promptUserForPermission(struct policy_query *): bundle codesign state: 1
[09/12/2016 21:43:46] 90 int promptUserForPermission(struct policy_query *): allow self container access: 1
[09/12/2016 21:43:46] 90 int promptUserForPermission(struct policy_query *): finding application icon for /Users/tomvanderwoerdt/Library/Application Support/Steam/Steam.AppBundle/Steam/Contents/MacOS/Frameworks/Steam Helper.app
[09/12/2016 21:43:46] 90 int promptUserForPermission(struct policy_query *): building parameters
[09/12/2016 21:43:46] 90 int promptUserForPermission(struct policy_query *): finding extension
[09/12/2016 21:43:46] 90 int promptUserForPermission(struct policy_query *): creating CFUserNotification
[09/12/2016 21:43:46] 90 int promptUserForPermission(struct policy_query *): waiting for response
[09/12/2016 21:44:25] 90 int main(int, char **): loadKext() returned 0

```

(Oh, and yes, disabling Little Flocker allows Steam to work.)

**Comment by jzdziarski** [comment]
its probably not allowing the popup to run, have you tried adding a rule to allow it? you might also try running it in learning mode, to get some rules built for it.

**Comment by TvdW** [comment]
I feel very stupid now. Yes, learning mode allowed it to learn these four rules :
![screen shot 2016-09-12 at 21 54 40](https://cloud.githubusercontent.com/assets/41807/18450673/3acfbba4-7934-11e6-8192-6da815b8cbc6.png)

Should I keep this ticket open so that some day the freeze can be addressed?

**Comment by jzdziarski** [comment]
it's not going to be fixable; if it can't prompt the user, it's going to deny access, and an app that doesn't know how to deal with that might hang the system.. that's one reason learning mode is there, glad it's working :)

**Comment by jzdziarski** [comment]
beta 6 is going to introduce window-level windows; this might actually fix this in a way I hadn't anticipated was doable

**Comment by jzdziarski** [comment]
I just pushed Beta 6, would be interested to know if the new windows I'm using are able to pop over Steam's full screen interface now. You could test by deleting your Steam rules, reloading, and running it again (with beta 6 of course).

**Comment by TvdW** [comment]
No luck, sorry. After removing the rules the system crashed as expected, and after updating it still happened. :-(

Btw, Steam doesn't have a full screen interface, it's a normal window and Little Flocker's popup shows properly. However, a few seconds after it shows, the system freezes.

**Comment by jzdziarski** [comment]
I tried running Steam over here and it prompted me just fine... but you might try pulling the nightly build and see if that makes any difference.

**Comment by jzdziarski** [comment]
ok it looks like steam runs a lot of unsigned binaries, and I did put a fix into the nightly build for this for another issue, so give that a spin, it may have had nothing to do with windowing problems after all.

**Comment by TvdW** [comment]
I don't have a code signing cert anymore, have been away from mac development for too long. Will update the ticket once Beta 7 gets released.

**Comment by jzdziarski** [comment]
the nightly is signed, you can grab it from the releases section

**Comment by TvdW** [comment]
Ah, indeed.

Tested it; works perfectly now!

I'd close the ticket, but it's already closed.

Thanks!

**Comment by jzdziarski** [comment]
yeah a little too fast on the trigger sorry
